# Generated by Django 2.0.13 on 2022-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=128, null=True, unique=True, verbose_name='이메일'),
        ),
    ]
