# Generated by Django 2.0.13 on 2022-04-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220418_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='학번'),
        ),
    ]
