# Generated by Django 2.0.13 on 2022-04-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220418_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='circles',
            field=models.CharField(choices=[('미가입', '미가입'), ('멀티미디어', '멀티미디어'), ('CE랩', 'CE랩')], max_length=18, null=True, verbose_name='랩실'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('컴퓨터공학과', '컴퓨터공학과')], max_length=24, null=True, verbose_name='학과'),
        ),
    ]
