# Generated by Django 3.2.13 on 2022-06-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220420_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('미래자동차공학과', '미래자동차공학과'), ('토목공학과', '토목공학과'), ('전자공학과', '전자공학과'), ('소프트웨어공학과', '소프트웨어공학과')], max_length=24, null=True, verbose_name='학과'),
        ),
    ]
