# Generated by Django 3.2.13 on 2022-05-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20220503_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='commits',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글수'),
        ),
    ]
