# Generated by Django 3.2.13 on 2022-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_commit_commits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='commits',
        ),
        migrations.AddField(
            model_name='photo',
            name='commits',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글수'),
        ),
    ]
